### ISSUE TITLE
Filter out non-existent modes in connector::Info::modes()

### ISSUE THREAD

**Issue by bjorn3** [Smithay/drm-rs#68]

**Comment by Drakulix** [comment]
Can you provide some more insight on this?
What kind of modes does `drm-rs` return, that are `non-existent`? This should be a direct representation of the mode retrieved from the ioctl and any "garbage" in that is likely the fault of the connected display. At least that is what I would expect?

**Comment by Slabity** [comment]
I've actually ran into this issue in the past when using a display with an invalid EDID checksum. Some fallback resolutions the monitor did not support were enumerated and could not be used.

However, I think this is something that needs to be fixed in the drivers that report the invalid modes. It might be possible to get around it by reading and parsing the display's EDID directly and creating modes from that, but that's not guaranteed to work especially if the EDID is incorrect to begin with.

**Comment by bjorn3** [comment]
If I recall correctly the non-existent modes had something like a size of 0 by 0 pixels. I also believe all non-existent modes were identical. I can't check it right now though.
