### ISSUE TITLE
0.3.x stable Rust support

### ISSUE THREAD

**Issue by katyo** [Smithay/drm-rs#72]
I was done some fixes for version which published on crates.
This is minor changes related to wider platforms support and updating dependencies.
But it important for me because my projects targeted to stable Rust.

Are you still accept PRs based on master branch for stable Rust?
Could you publish 0.3.x releases on crates.io?

**Comment by Drakulix** [comment]
As long as your PR does not break the 0.3.x API, I am open to accept it.

Note: The develop branch (which is due to become 0.4) will not require nightly forever. Right now all remaining nightly-features are actually unused and an eventual 0.4 release should be able to run on stable. Feel free to experiment with it.

**Comment by katyo** [comment]
@Drakulix I'm glad to hear that, because nightly rust still barrier for me for many reasons.
Could you edit readme to reflect such fact?

**Comment by Slabity** [comment]
We used the `untagged_unions` and `nll` features, which is now in stable rust. The only other nightly feature used is `slice_patterns`, which is only in the examples.

Removing all three of these allows it to be compiled on stable without any issues. I will make a new release that does not require nightly.

**Comment by Slabity** [comment]
I think this issue can be closed as we don't require nightly. If there's still a problem here feel free to open it.
