### ISSUE TITLE
[Question] Failed to create framebuffer

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [Smithay/drm-rs#84]
Hi!
When I'm trying to to run `kms-interacive` example in dev branch it fails when creating framebuffer with `InvalidArgument` error. I've checked that in my case it's converted from `SystemError` which comes from `ioctl::mode::add_fb` function. But it's not clear what is exactly wrong (just in case I'm of course running it without terminal emulator). 

Can you suggest what could go wrong?

**Comment by Drakulix** [comment]
Well, I am not sure if depth or bpp values of "1" are actually valid.

Can you try chaging the arguments of [add_framebuffer](https://github.com/Smithay/drm-rs/blob/develop/examples/kms_interactive.rs#L40) in `kms-interactive` to something more reasonable like `&db, 32, 32`? That might fix it.

**Comment by MarijnS95** [comment]
@Drakulix Noticed the same while updating my toy project to `develop` and trying to understand why the previous implementation passed `32` for both fields (through `fn bpp()` and `fn depth()`), passing `32` indeed fixes the error (here and in `legacy_modeset`, `atomic_modeset`).

**Comment by Drakulix** [comment]
Then please someone make a PR and fix the examples :sweat_smile: .
For a correct mapping between color-formats and bpp/depth, we would need to maintain a table ourselves, which I would rather not do (`drm-fourcc` has a lot of formats). (Which is why `depth()` and `bpp()` were dropped.)

But that should not be an issue of the examples, as they always use a hard-coded format. So we should just set the example to correct values for the given color format.

**Comment by Drakulix** [comment]
Closed via #85
